---

# deploy one stack
- name: Deploy one service
  include_tasks: loop_deploy_inner.yml stack1="{{ stack }}"
  when: stack is defined

# deploy stacks
- name: Deploy each service
  include_tasks: loop_deploy_inner.yml
  with_items: "{{ deploy_stack_stacks }}"
  loop_control:
    loop_var: stack1
  when: deploy_stack_stacks is defined and ( deploy_stack_name is not defined or stack1.name == deploy_stack_name )

#
#
## deploy multiple stacks
#- name: Deploy services
#  include_tasks: loop_deploy_outer.yml
#  when: stack is not defined
